defaults: &defaults
  dailies:
    send_not: 0
    send_ontime: 1
    send_overdate: 2

  users:
    identity_admin: 10
    identity_teacher: 1
    identity_student: 2
    identity_admin_string: 管理员
    identity_teacher_string: 教师
    identity_student_string: 学生

  papers:
    status_submit: 1
    status_accept: 2
    status_publish: 3
    status_submit_string: 已投稿
    status_accept_string: 已录用
    status_publish_string: 已发表

  projects:
    category_vertical: 1
    category_horizontal: 2
    category_vertical_string: 纵向
    category_horizontal_string: 横向
    status_plan: 1
    status_writing: 2
    status_applying: 3
    status_reviewing: 4
    status_proceeding: 5
    status_acceptance: 6
    status_finish: 7
    status_plan_string: 规划中
    status_writing_string: 撰写中
    status_applying_string: 申报中
    status_reviewing_string: 评审中
    status_proceeding_string: 进行中
    status_acceptance_string: 验收中
    status_finish_string: 已结束

  patents:
    status_plan: 1
    status_writing: 2
    status_processing: 3
    status_publication: 4
    status_reality: 5
    status_authorization: 6
    status_plan_string: 有想法
    status_writing_string: 撰写中
    status_processing_string: 受理中
    status_publication_string: 公开中
    status_reality_string: 实审中
    status_authorization_string: 已授权

  documents:
    category_project: 1
    category_paper: 2
    category_patent: 3

  histories:
    category_project: 1
    category_paper: 2
    category_patent: 3
    category_daily: 4
    category_daily_comment: 5
    action_create: 1
    action_update: 2
    action_destroy: 3
    action_create_string: 新建了
    action_update_string: 修改了
    action_destroy_string: 删除了

  plans:
    status_none: 1
    status_active: 2
    status_finish: 3
    status_canceled: 4
    status_postponed: 5
    status_none_string: 未完成
    status_active_string: 进行中
    status_finish_string: 已完成
    status_canceled_string: 已取消
    status_postponed_string: 已延迟

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
