defaults: &defaults
  dailies:
    send_not: 0
    send_ontime: 1
    send_overdate: 2

  users:
    identity_admin: 10
    identity_teacher: 1
    identity_student: 2
    identity_admin_string: 管理员
    identity_teacher_string: 教师
    identity_student_string: 学生

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
